### ISSUE TITLE
the NetworkClientSystem spawned dictionnary wont get cleared if the transport disconnect the client

### ISSUE THREAD

**Issue by Nyert** [vis2k/DOTSNET#53] opened 2021-09-27 19:17 UTC
**Describe the bug**
the NetworkClientSystem spawned dictionnary wont get cleared if the transport disconnect the client.

**[IMPORTANT] How can we reproduce the issue, step by step:**
1. make a build version and run it
2. play in the editor 
3. start the server 
4. connect with the build version as a client
5. stop the server in the editor
6. start the server again
7. reconnect with the build 
8. it should crash (access violation error) 

**Expected behavior**
should not crash and connect instead

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by miwarnec** [comment] 2021-12-03 13:06
tried it without issues on 2021.2.3 and latest dotsnet.
are you sure the bug still exists?
do you have a stack trace?

<img width="515" alt="2021-12-03_14-05-57@2x" src="https://user-images.githubusercontent.com/16416509/144607374-30786422-6517-4983-a0b9-970ac27bf9ae.png">

**Comment by miwarnec** [comment] 2021-12-03 13:07
looks like volunatry Disconnect() clears state, but ONDisconnect doesn't though

**Comment by miwarnec** [comment] 2021-12-03 13:13
ironically delta snapshots auto spawns all the previous ones which are not in first spawn message.
but still need to refactor the code so that voluntary and involuntary disconnects both call OnDisconnected

**Comment by miwarnec** [comment] 2021-12-03 13:36
added a test to reproduce & to avoid it in the future:
<img width="418" alt="2021-12-03_14-36-26@2x" src="https://user-images.githubusercontent.com/16416509/144611284-d0e8f65d-916f-460c-8358-f00d1a3623c1.png">

**Comment by miwarnec** [comment] 2021-12-03 14:45
fixed in next version, thanks

**Closed as completed by miwarnec** 2021-12-03 14:45 UTC
Labels: can't reproduce
